### PR TITLE
Add OnSwitchTemplateParsed - System-Event

### PR DESCRIPTION
**Pull request by Bruno17**
I need to sanitize the output, after switching and processing the template.
In my case sanitizing and altering the output for AMP.
Works great with a plugin at this new System-Event.

### CODE REVIEW

**Comment by Jako** [comment]
Thanks!

**Comment by Jako** [comment]
Maybe you want to write a small code example for the README?

**Comment by Bruno17** [comment]
Will do, as soon, as my AMP - switcher is working so far

**Comment by Bruno17** [comment]
here is the plugin (not so small), which I'm working on, currently
https://github.com/Bruno17/AMPX/blob/master/core/components/ampx/elements/plugins/ampx.plugin.php

but I can give a smaller example, if you want. Any ideas for a small example?

**Pull request merged**
